language: python

addons:
  apt:
    packages:
    - python-genometools
cache:
  directories:
  - "build"
  - "$HOME/.cache/pip"
python:
  - "2.7"
sudo: required
dist: trusty
script:
  - "python setup.py nosetests"
