#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  Author: Sascha Steinbiss <ss34@sanger.ac.uk>
#  Copyright (c) 2015 Genome Research Ltd
#
#  Permission to use, copy, modify, and distribute this software for any
#  purpose with or without fee is hereby granted, provided that the above
#  copyright notice and this permission notice appear in all copies.
#
#  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#  ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#  OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

import argparse
import eupathtables
import gt
import sys

parser = argparse.ArgumentParser(description='Convert EuPathDB flat file ' +
                                              'format into Companion '
                                              'compatible reference input.')
parser.add_argument('infile', metavar='FILE', type=str, help='input file')
parser.add_argument('-g', '--gaf', metavar='FILE', type=str,
                    help='GAF file to write', dest='gaffile')
parser.add_argument('-t', '--taxon', metavar='TID', type=int,
                    help='taxon ID to use in GAF file', dest='taxon_id')
args = parser.parse_args()

table_in_stream = eupathtables.TableInStream(args.infile, args.gaffile,
                                             args.taxon_id)
gff_out_stream = gt.extended.GFF3OutStream(table_in_stream)

fn = gff_out_stream.next_tree()
while fn:
    fn = gff_out_stream.next_tree()